- name: build app
  hosts: build
  become: yes

  tasks:
  - name: ensure maven package is present
    apt:
     name: maven
     state: present

  - name: ensure git package is present
    apt:
     name: git
     state: present
     update_cache: yes

  - name: check if there is a git repository
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /home/webapp
     clone: yes

  - name: run maven
    shell: cd /home/webapp && mvn package

  - name: send war file to master
    fetch:
     src: /home/webapp/target/hello-1.0.war
     dest: /opt


- name: deploy app
  hosts: deploy
  become: yes

  tasks:
  - name: ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: ensure tomcat package is present
    apt:
     name: tomcat8
     state: present

  - name:
    copy: copy war file from master
      src: /opt/84.201.160.144/home/webapp/target/hello-1.0.war
      dest: /var/lib/tomcat8/webapps

  - name: restart tomcat8
    service:
     name: tomcat8
     state: restarted