- name: build app
  hosts: build
  become: yes

  tasks:
  - name: ensure maven package is present
    apt:
     name: maven
     state: present

  - name: ensure git package is present
    apt:
     name: git
     state: present
     update_cache: yes

  - name: check if there is a git repository
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /home/webapp
     clone: yes

  - name: run maven
    shell: cd /home/webapp && mvn package

  - name: send war file to deploy_server
    fetch:
     src: /home/webapp/target/hello-1.0.war
     dest: /home


- name: deploy app
  hosts: deploy
  become: yes

  tasks:
  - name: ensure jdk package is present
    apt:
     name: default-jdk
     state: present

  - name: ensure tomcat package is present
    apt:
     name: tomcat8
     state: present

#  - name: copy war file hello-1.0
#    synchronize: src=/home/webapp/target/hello-1.0.war/build  dest=/var/lib/tomcat8/webapps/deploy
#    delegate_to: build
  - name:
    copy:
      src: /home/84.201.160.44/home/webaaps/target/hello-1.0.war
      dest: /var/lib/tomcat8/webapps

  - name: restart tomcat8
    service:
     name: tomcat8
     state: restart